export const CAR_CATALOG: Record<string, string[]> = {
  Toyota: ["Camry", "Corolla", "RAV4", "Land Cruiser", "Land Cruiser Prado", "Highlander", "C-HR", "Fortuner"],
  Kia: ["Rio", "Ceed", "Cerato", "K5", "Optima", "Sportage", "Sorento", "Seltos", "Carnival"],
  Hyundai: ["Solaris", "Elantra", "Sonata", "Tucson", "Santa Fe", "Creta", "Palisade", "Staria"],
  BMW: ["1 Series", "3 Series", "5 Series", "7 Series", "X1", "X3", "X4", "X5", "X6", "X7"],
  Mercedes: ["A-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "V-Class"],
  Audi: ["A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8"],
  Volkswagen: ["Polo", "Jetta", "Passat", "Golf", "Tiguan", "Touareg", "Teramont", "Multivan"],
  Skoda: ["Rapid", "Octavia", "Superb", "Fabia", "Karoq", "Kodiaq", "Yeti"],
  Renault: ["Logan", "Sandero", "Duster", "Arkana", "Kaptur", "Megane", "Koleos"],
  Nissan: ["Almera", "Teana", "Qashqai", "X-Trail", "Murano", "Pathfinder", "Terrano", "Juke"],
  Lexus: ["ES", "IS", "LS", "NX", "RX", "GX", "LX", "UX"],
  Chery: ["Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo 8", "Omoda C5"],
  Geely: ["Coolray", "Atlas", "Atlas Pro", "Monjaro", "Tugella", "Emgrand", "Okavango"],
  Haval: ["Jolion", "F7", "F7x", "Dargo", "H9", "M6"],
  Lada: ["Granta", "Vesta", "Niva", "Niva Travel", "Largus", "XRAY"],
  Mazda: ["3", "6", "CX-3", "CX-5", "CX-7", "CX-9"],
  Mitsubishi: ["ASX", "Eclipse Cross", "Lancer", "Outlander", "Pajero", "Pajero Sport"],
  Ford: ["Focus", "Mondeo", "Kuga", "Explorer", "Transit", "Mustang"],
  Chevrolet: ["Aveo", "Cruze", "Captiva", "Tahoe", "Trailblazer", "Niva"],
  Honda: ["Civic", "Accord", "CR-V", "Pilot", "Fit", "HR-V"],
  Porsche: ["Macan", "Cayenne", "Panamera", "911", "Taycan"],
  Volvo: ["S60", "S90", "XC40", "XC60", "XC90", "V60"],
  Subaru: ["Forester", "Outback", "XV", "Legacy", "Impreza"],
  Peugeot: ["308", "408", "508", "2008", "3008", "5008", "Partner"],
  Citroen: ["C4", "C5 Aircross", "Berlingo", "Jumpy", "SpaceTourer"],
  Exeed: ["LX", "TXL", "VX", "RX"],
  Tank: ["300", "500"],
  Zeekr: ["001", "007", "009", "X"],
  LiXiang: ["L6", "L7", "L8", "L9"],
};

export const CAR_MAKES = Object.keys(CAR_CATALOG);
