export const BUSINESS = {
  name: "ОМУТ",
  fullName: "Детейлинг-студия «Омут»",
  tagline: "Глубокая забота о вашем автомобиле",
  city: "Самара",
  address: "ул. Галактионовская, 49",
  addressFull: "Самара, ул. Галактионовская, 49",
  district: "Самарский район, центр",
  landmark: "остановка «Некрасовская» · трамваи 5, 20, 22",
  phone: "+7 (000) 000-00-00",
  phoneHref: "tel:+70000000000",
  whatsapp: "https://wa.me/70000000000",
  telegram: "https://t.me/",
  instagram: "https://instagram.com/",
  hours: "Ежедневно, 09:00–21:00",
  mapLat: 53.1959,
  mapLng: 50.1,
} as const;

// Initial services catalog (seed). Prices are "from", body class B, in RUB.
export const SEED_SERVICES = [
  {
    slug: "detailing-wash",
    title: "Детейлинг-мойка",
    shortDesc: "Безопасная двухфазная мойка без вихревых царапин",
    category: "wash",
    basePrice: 1400,
    durationMin: 90,
    popular: true,
    sortOrder: 10,
  },
  {
    slug: "light-polish",
    title: "Лёгкая полировка",
    shortDesc: "Защитная полировка, убирает паутинку и мелкие риски",
    category: "polish",
    basePrice: 5500,
    durationMin: 240,
    popular: true,
    sortOrder: 20,
  },
  {
    slug: "deep-polish",
    title: "Глубокая полировка",
    shortDesc: "Абразивное восстановление ЛКП до зеркального блеска",
    category: "polish",
    basePrice: 11000,
    durationMin: 480,
    sortOrder: 30,
  },
  {
    slug: "ceramic",
    title: "Керамическое покрытие",
    shortDesc: "Долговременная защита и гидрофоб, глубина цвета",
    category: "protection",
    basePrice: 9500,
    durationMin: 600,
    popular: true,
    sortOrder: 40,
  },
  {
    slug: "liquid-glass",
    title: "Жидкое стекло",
    shortDesc: "Яркий блеск и водоотталкивающий эффект",
    category: "protection",
    basePrice: 7000,
    durationMin: 300,
    sortOrder: 50,
  },
  {
    slug: "interior-cleaning",
    title: "Химчистка салона",
    shortDesc: "Глубокая чистка, удаление пятен и запахов",
    category: "interior",
    basePrice: 8500,
    durationMin: 360,
    popular: true,
    sortOrder: 60,
  },
  {
    slug: "ozone",
    title: "Озонация салона",
    shortDesc: "Устранение запахов и дезинфекция",
    category: "interior",
    basePrice: 1500,
    durationMin: 60,
    sortOrder: 70,
  },
  {
    slug: "headlight-polish",
    title: "Полировка фар",
    shortDesc: "Прозрачность и яркость света, пара фар",
    category: "polish",
    basePrice: 1200,
    durationMin: 60,
    sortOrder: 80,
  },
  {
    slug: "anti-rain",
    title: "Антидождь",
    shortDesc: "Гидрофоб на стёкла, лучший обзор в непогоду",
    category: "protection",
    basePrice: 2500,
    durationMin: 60,
    sortOrder: 90,
  },
  {
    slug: "presale",
    title: "Предпродажная подготовка",
    shortDesc: "Комплекс: мойка + полировка + химчистка",
    category: "complex",
    basePrice: 18900,
    durationMin: 600,
    sortOrder: 100,
  },
] as const;

export const SERVICE_CATEGORIES: Record<string, string> = {
  wash: "Мойка",
  polish: "Полировка",
  protection: "Защитные покрытия",
  interior: "Уход за салоном",
  complex: "Комплексы",
  other: "Другое",
};
